create extension if not exists pgcrypto;
create extension if not exists citext;

create sequence if not exists public.report_number_seq start 1;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  employee_code text not null unique,
  display_name text not null,
  email citext not null unique,
  role text not null default 'user' check (role in ('user', 'admin')),
  can_view_others boolean not null default false,
  can_copy_others boolean not null default false,
  must_reset_password boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profile_login_aliases (
  alias citext primary key,
  user_id uuid not null references public.profiles(id) on delete cascade
);

create table if not exists public.reports (
  id text primary key check (id ~ '^BR-[0-9]{8}$'),
  owner_id uuid not null references public.profiles(id),
  report_name text not null default '',
  status text not null default '',
  days numeric not null default 0,
  start_date date,
  end_date date,
  destination text not null default '',
  payment_currency text not null default 'TWD',
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expense_items (
  id uuid primary key default gen_random_uuid(),
  report_id text not null references public.reports(id) on delete cascade,
  category text not null check (category in (
    'Flight', 'Accommodation', 'Rental Car', 'Gas', 'Parking',
    'Transportation', 'Internet', 'Social', 'Gift', 'Luggage Fee',
    'Handing Fee', 'Per Diem', 'Advance Payment', 'Others', 'Lunch & Learn'
  )),
  sequence integer not null check (sequence > 0),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (report_id, category, sequence)
);

create table if not exists public.countries (
  name text primary key
);

create table if not exists public.cities (
  name text primary key
);

create table if not exists public.flight_schedules (
  id bigint generated by default as identity primary key,
  flight_number text not null,
  week text,
  departure_airport_id text,
  arrival_airport_id text,
  departure_time text,
  arrival_time text,
  cross_day text
);

create table if not exists public.exchange_rates (
  currency text not null,
  rate_date date not null,
  rate numeric not null check (rate > 0),
  source text not null,
  fetched_at timestamptz not null default now(),
  primary key (currency, rate_date)
);

create index if not exists reports_owner_created_idx
  on public.reports (owner_id, created_at desc);
create index if not exists reports_created_idx
  on public.reports (created_at desc);
create index if not exists expense_items_report_category_idx
  on public.expense_items (report_id, category, sequence);
create index if not exists expense_items_data_gin_idx
  on public.expense_items using gin (data);
create index if not exists flight_schedules_number_idx
  on public.flight_schedules (flight_number);
create index if not exists cities_name_pattern_idx
  on public.cities (name text_pattern_ops);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
drop trigger if exists reports_set_updated_at on public.reports;
create trigger reports_set_updated_at before update on public.reports
for each row execute function public.set_updated_at();
drop trigger if exists expense_items_set_updated_at on public.expense_items;
create trigger expense_items_set_updated_at before update on public.expense_items
for each row execute function public.set_updated_at();

create or replace function public.current_profile()
returns public.profiles
language sql stable security definer set search_path = public
as $$
  select p from public.profiles p where p.id = auth.uid()
$$;

create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select coalesce((select role = 'admin' from public.profiles where id = auth.uid()), false)
$$;

create or replace function public.can_view_others()
returns boolean
language sql stable security definer set search_path = public
as $$
  select coalesce((select can_view_others from public.profiles where id = auth.uid()), false)
$$;

create or replace function public.can_view_report(target_report_id text)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1
    from public.reports r
    join public.profiles p on p.id = auth.uid()
    where r.id = target_report_id
      and (r.owner_id = auth.uid() or p.role = 'admin' or p.can_view_others)
  )
$$;

create or replace function public.can_edit_report(target_report_id text)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1
    from public.reports r
    join public.profiles p on p.id = auth.uid()
    where r.id = target_report_id
      and r.status = ''
      and (r.owner_id = auth.uid() or p.role = 'admin')
  )
$$;

alter table public.profiles enable row level security;
alter table public.profile_login_aliases enable row level security;
alter table public.reports enable row level security;
alter table public.expense_items enable row level security;
alter table public.countries enable row level security;
alter table public.cities enable row level security;
alter table public.flight_schedules enable row level security;
alter table public.exchange_rates enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated
using (
  id = auth.uid()
  or public.is_admin()
  or public.can_view_others()
);
drop policy if exists profiles_update_admin on public.profiles;
create policy profiles_update_admin on public.profiles for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists reports_select on public.reports;
create policy reports_select on public.reports for select to authenticated
using (public.can_view_report(id));

drop policy if exists expense_items_select on public.expense_items;
create policy expense_items_select on public.expense_items for select to authenticated
using (public.can_view_report(report_id));

drop policy if exists countries_read on public.countries;
create policy countries_read on public.countries for select to anon, authenticated using (true);
drop policy if exists cities_read on public.cities;
create policy cities_read on public.cities for select to anon, authenticated using (true);
drop policy if exists flight_schedules_read on public.flight_schedules;
create policy flight_schedules_read on public.flight_schedules for select to authenticated using (true);
drop policy if exists exchange_rates_read on public.exchange_rates;
create policy exchange_rates_read on public.exchange_rates for select to authenticated using (true);

create or replace function public.resolve_login(identifier text)
returns table(email text, must_reset_password boolean)
language sql stable security definer set search_path = public
as $$
  select p.email::text, p.must_reset_password
  from public.profile_login_aliases a
  join public.profiles p on p.id = a.user_id
  where lower(a.alias::text) = lower(trim(identifier))
  union all
  select p.email::text, p.must_reset_password
  from public.profiles p
  where lower(p.email::text) = lower(trim(identifier))
    and not exists (
      select 1 from public.profile_login_aliases a
      where lower(a.alias::text) = lower(trim(identifier))
    )
  limit 1
$$;
grant execute on function public.resolve_login(text) to anon, authenticated;

create or replace function public.complete_password_reset()
returns void language sql security definer set search_path = public
as $$
  update public.profiles
  set must_reset_password = false
  where id = auth.uid()
$$;
grant execute on function public.complete_password_reset() to authenticated;

create or replace function public.handle_new_auth_user()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  code text;
  label text;
begin
  code := coalesce(nullif(new.raw_user_meta_data ->> 'employee_code', ''), 'U-' || substr(new.id::text, 1, 8));
  label := coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1));
  insert into public.profiles (id, employee_code, display_name, email)
  values (new.id, code, label, new.email)
  on conflict (id) do nothing;
  insert into public.profile_login_aliases (alias, user_id)
  values (code, new.id), (label, new.id)
  on conflict (alias) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.create_report(initial_usd_rate numeric default 1)
returns text language plpgsql security definer set search_path = public
as $$
declare
  profile public.profiles;
  new_id text;
begin
  select * into profile from public.profiles where id = auth.uid();
  if profile.id is null then raise exception 'Profile not found'; end if;
  new_id := 'BR-' || lpad(nextval('public.report_number_seq')::text, 8, '0');
  insert into public.reports (id, owner_id, data)
  values (
    new_id,
    auth.uid(),
    jsonb_build_object(
      '報告編號', new_id,
      '用戶編號', profile.employee_code,
      '員工姓名', profile.display_name,
      '報告名稱', '',
      '狀態', '',
      '商旅天數', 0,
      '支付幣別', 'TWD',
      'USD匯率', greatest(coalesce(initial_usd_rate, 1), 0.000001)
    )
  );
  return new_id;
end;
$$;
grant execute on function public.create_report(numeric) to authenticated;

create or replace function public.jsonb_number(value jsonb, variadic keys text[])
returns numeric language plpgsql immutable as $$
declare key text; parsed numeric;
begin
  foreach key in array keys loop
    begin
      if value ? key and nullif(regexp_replace(value ->> key, '[^0-9.-]', '', 'g'), '') is not null then
        parsed := regexp_replace(value ->> key, '[^0-9.-]', '', 'g')::numeric;
        return parsed;
      end if;
    exception when others then null;
    end;
  end loop;
  return 0;
end;
$$;

create or replace function public.recalculate_report(target_report_id text)
returns void language plpgsql security definer set search_path = public
as $$
declare
  totals jsonb := jsonb_build_object(
    '機票費總額', 0, '機票費USD總額', 0,
    '個人住宿費總額', 0, '個人住宿費USD總額', 0,
    '總體住宿費總額', 0, '總體住宿費USD總額', 0,
    '個人租車費總額', 0, '個人租車費USD總額', 0,
    '總體租車費總額', 0, '總體租車費USD總額', 0,
    '交通運輸費總額', 0, '交通運輸費USD總額', 0,
    '瓦斯費總額', 0, '瓦斯費USD總額', 0,
    '停車費總額', 0, '停車費USD總額', 0,
    '網路費總額', 0, '網路費USD總額', 0,
    '社交費總額', 0, '社交費USD總額', 0,
    '禮品費總額', 0, '禮品費USD總額', 0,
    '行李費總額', 0, '行李費USD總額', 0,
    '手續費總額', 0, '手續費USD總額', 0,
    '日支費總額', 0, '日支費USD總額', 0,
    '預支費用總額', 0, '預支費用USD總額', 0,
    '午餐與學費總額', 0, '午餐與學費USD總額', 0,
    '其他費用總額', 0, '其他費用USD總額', 0
  );
  row record;
  amount numeric;
  personal numeric;
  grand numeric := 0;
  personal_grand numeric := 0;
  advance_total numeric := 0;
  days_count numeric;
  usd_rate numeric;
  header jsonb;
  twd_key text;
  usd_key text;
begin
  select
    data,
    greatest(days, 0),
    coalesce(
      nullif((
        select max(public.jsonb_number(i.data, '匯率'))
        from public.expense_items i
        where i.report_id = target_report_id
          and upper(coalesce(i.data ->> '幣別', '')) = 'USD'
      ), 0),
      nullif(public.jsonb_number(data, 'USD匯率'), 0),
      1
    )
    into header, days_count, usd_rate
  from public.reports where id = target_report_id for update;
  if not found then raise exception 'Report not found'; end if;

  for row in
    select category,
      sum(case when category in ('Accommodation','Rental Car')
        then public.jsonb_number(data, 'TWD總體金額', 'TWD總額')
        else public.jsonb_number(data, 'TWD金額') end) as overall,
      sum(case when category in ('Accommodation','Rental Car')
        then public.jsonb_number(data, 'TWD個人金額', 'TWD個人')
        else public.jsonb_number(data, 'TWD金額') end) as personal
    from public.expense_items where report_id = target_report_id group by category
  loop
    amount := coalesce(row.overall, 0);
    personal := coalesce(row.personal, 0);
    if row.category = 'Advance Payment' then
      advance_total := amount;
    else
      grand := grand + amount;
      personal_grand := personal_grand + personal;
    end if;
    twd_key := case row.category
        when 'Flight' then '機票費總額'
        when 'Accommodation' then '總體住宿費總額'
        when 'Rental Car' then '總體租車費總額'
        when 'Transportation' then '交通運輸費總額'
        when 'Gas' then '瓦斯費總額'
        when 'Parking' then '停車費總額'
        when 'Internet' then '網路費總額'
        when 'Social' then '社交費總額'
        when 'Gift' then '禮品費總額'
        when 'Luggage Fee' then '行李費總額'
        when 'Handing Fee' then '手續費總額'
        when 'Per Diem' then '日支費總額'
        when 'Advance Payment' then '預支費用總額'
        when 'Lunch & Learn' then '午餐與學費總額'
        else '其他費用總額'
      end;
    usd_key := case row.category
        when 'Flight' then '機票費USD總額'
        when 'Accommodation' then '總體住宿費USD總額'
        when 'Rental Car' then '總體租車費USD總額'
        when 'Transportation' then '交通運輸費USD總額'
        when 'Gas' then '瓦斯費USD總額'
        when 'Parking' then '停車費USD總額'
        when 'Internet' then '網路費USD總額'
        when 'Social' then '社交費USD總額'
        when 'Gift' then '禮品費USD總額'
        when 'Luggage Fee' then '行李費USD總額'
        when 'Handing Fee' then '手續費USD總額'
        when 'Per Diem' then '日支費USD總額'
        when 'Advance Payment' then '預支費用USD總額'
        when 'Lunch & Learn' then '午餐與學費USD總額'
        else '其他費用USD總額'
      end;
    totals := totals || jsonb_build_object(
      twd_key, round(amount),
      usd_key, round(amount / usd_rate, 2)
    );
    if row.category = 'Accommodation' then
      totals := totals || jsonb_build_object(
        '個人住宿費總額', round(personal),
        '個人住宿費USD總額', round(personal / usd_rate, 2)
      );
    elsif row.category = 'Rental Car' then
      totals := totals || jsonb_build_object(
        '個人租車費總額', round(personal),
        '個人租車費USD總額', round(personal / usd_rate, 2)
      );
    end if;
  end loop;

  totals := totals || jsonb_build_object(
    'USD匯率', usd_rate,
    '合計TWD個人總額', round(personal_grand),
    '合計TWD總體總額', round(grand),
    '預支費用總額', round(advance_total),
    '合計USD個人總額', round(personal_grand / usd_rate, 2),
    '合計USD總體總額', round(grand / usd_rate, 2),
    '合計TWD個人平均', case when days_count > 0 then round(personal_grand / days_count) else round(personal_grand) end,
    '合計TWD總體平均', case when days_count > 0 then round(grand / days_count) else round(grand) end,
    '合計USD個人平均', case when days_count > 0 then round(personal_grand / usd_rate / days_count, 2) else round(personal_grand / usd_rate, 2) end,
    '合計USD總體平均', case when days_count > 0 then round(grand / usd_rate / days_count, 2) else round(grand / usd_rate, 2) end
  );
  update public.reports set data = data || totals where id = target_report_id;
end;
$$;

create or replace function public.upsert_expense_item(
  target_report_id text,
  target_category text,
  target_sequence integer,
  item_data jsonb
) returns integer language plpgsql security definer set search_path = public
as $$
declare seq integer;
begin
  if not public.can_edit_report(target_report_id) then raise exception 'Report is locked or you cannot edit it'; end if;
  perform 1 from public.reports where id = target_report_id for update;
  if target_sequence is null then
    select coalesce(max(sequence), 0) + 1 into seq
    from public.expense_items where report_id = target_report_id and category = target_category;
    insert into public.expense_items (report_id, category, sequence, data)
    values (target_report_id, target_category, seq, item_data || jsonb_build_object('報告編號', target_report_id, '次序', seq));
  else
    seq := target_sequence;
    update public.expense_items
      set data = item_data || jsonb_build_object('報告編號', target_report_id, '次序', seq)
    where report_id = target_report_id and category = target_category and sequence = seq;
    if not found then raise exception 'Expense item not found'; end if;
  end if;
  perform public.recalculate_report(target_report_id);
  return seq;
end;
$$;
grant execute on function public.upsert_expense_item(text,text,integer,jsonb) to authenticated;

create or replace function public.delete_expense_item(target_report_id text, target_category text, target_sequence integer)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if not public.can_edit_report(target_report_id) then raise exception 'Report is locked or you cannot edit it'; end if;
  delete from public.expense_items
  where report_id = target_report_id and category = target_category and sequence = target_sequence;
  perform public.recalculate_report(target_report_id);
end;
$$;
grant execute on function public.delete_expense_item(text,text,integer) to authenticated;

create or replace function public.update_report_details(
  target_report_id text,
  new_name text default null,
  new_days numeric default null,
  new_start date default null,
  new_end date default null,
  new_destination text default null,
  new_currency text default null,
  new_usd_rate numeric default null
) returns void language plpgsql security definer set search_path = public
as $$
begin
  if not public.can_edit_report(target_report_id) then raise exception 'Report is locked or you cannot edit it'; end if;
  update public.reports set
    report_name = coalesce(new_name, report_name),
    days = coalesce(new_days, days),
    start_date = coalesce(new_start, start_date),
    end_date = coalesce(new_end, end_date),
    destination = coalesce(new_destination, destination),
    payment_currency = coalesce(new_currency, payment_currency),
    data = data || jsonb_strip_nulls(jsonb_build_object(
      '報告名稱', new_name, '商旅天數', new_days, '商旅起始日', new_start,
      '商旅結束日', new_end, '出差國家', new_destination, '支付幣別', new_currency,
      'USD匯率', new_usd_rate,
      '是否手動天數', case when new_days is not null or new_start is not null or new_end is not null then 'Y' end
    ))
  where id = target_report_id;
  perform public.recalculate_report(target_report_id);
end;
$$;
grant execute on function public.update_report_details(text,text,numeric,date,date,text,text,numeric) to authenticated;

create or replace function public.set_report_status(target_report_id text, new_status text)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Administrator permission required'; end if;
  update public.reports set status = coalesce(new_status, ''), data = data || jsonb_build_object('狀態', coalesce(new_status, ''))
  where id = target_report_id;
  if not found then raise exception 'Report not found'; end if;
end;
$$;
grant execute on function public.set_report_status(text,text) to authenticated;

create or replace function public.delete_report(target_report_id text)
returns void language plpgsql security definer set search_path = public
as $$
declare target public.reports;
begin
  select * into target from public.reports where id = target_report_id for update;
  if target.id is null then return; end if;
  if target.status <> '' then raise exception 'Cannot delete a report with an existing status'; end if;
  if target.owner_id <> auth.uid() and not public.is_admin() then raise exception 'Permission denied'; end if;
  delete from public.reports where id = target_report_id;
end;
$$;
grant execute on function public.delete_report(text) to authenticated;

create or replace function public.copy_report(source_report_id text)
returns text language plpgsql security definer set search_path = public
as $$
declare source public.reports; profile public.profiles; new_id text;
begin
  select * into source from public.reports where id = source_report_id;
  select * into profile from public.profiles where id = auth.uid();
  if source.id is null or profile.id is null then raise exception 'Source report or profile not found'; end if;
  if source.owner_id <> auth.uid() and not (profile.role = 'admin' or profile.can_copy_others) then
    raise exception 'Permission denied';
  end if;
  new_id := 'BR-' || lpad(nextval('public.report_number_seq')::text, 8, '0');
  insert into public.reports (id, owner_id, report_name, days, start_date, end_date, destination, payment_currency, data)
  values (
    new_id, auth.uid(), source.report_name || ' (複製)', source.days, source.start_date, source.end_date,
    source.destination, source.payment_currency,
    source.data || jsonb_build_object('報告編號', new_id, '用戶編號', profile.employee_code, '員工姓名', profile.display_name,
      '報告名稱', source.report_name || ' (複製)', '狀態', '')
  );
  insert into public.expense_items (report_id, category, sequence, data)
  select new_id, category, sequence, data || jsonb_build_object('報告編號', new_id)
  from public.expense_items where report_id = source_report_id;
  perform public.recalculate_report(new_id);
  return new_id;
end;
$$;
grant execute on function public.copy_report(text) to authenticated;

create or replace function public.copy_items(target_report_id text, source_item_ids uuid[])
returns integer language plpgsql security definer set search_path = public
as $$
declare source record; seq integer; copied integer := 0;
begin
  if not public.can_edit_report(target_report_id) then raise exception 'Report is locked or you cannot edit it'; end if;
  perform 1 from public.reports where id = target_report_id for update;
  for source in
    select * from public.expense_items where id = any(source_item_ids) and public.can_view_report(report_id)
  loop
    select coalesce(max(sequence), 0) + 1 into seq
    from public.expense_items where report_id = target_report_id and category = source.category;
    insert into public.expense_items (report_id, category, sequence, data)
    values (target_report_id, source.category, seq, source.data || jsonb_build_object('報告編號', target_report_id, '次序', seq));
    copied := copied + 1;
  end loop;
  perform public.recalculate_report(target_report_id);
  return copied;
end;
$$;
grant execute on function public.copy_items(text,uuid[]) to authenticated;

create or replace function public.sync_report_sequence()
returns bigint language plpgsql security definer set search_path = public
as $$
declare maximum bigint;
begin
  select coalesce(max(substring(id from 4)::bigint), 0) into maximum from public.reports;
  perform setval('public.report_number_seq', greatest(maximum, 1), maximum > 0);
  return maximum;
end;
$$;

create or replace view public.report_summaries
with (security_invoker = true) as
select
  r.id,
  r.owner_id,
  p.employee_code,
  p.display_name,
  r.days,
  r.start_date,
  r.end_date,
  r.status,
  r.created_at,
  r.report_name,
  r.destination,
  r.payment_currency,
  public.jsonb_number(r.data, '合計TWD總體總額') as total_twd,
  public.jsonb_number(r.data, '預支費用總額') as advance_twd,
  public.jsonb_number(r.data, '合計USD總體總額') as total_usd,
  coalesce(nullif(public.jsonb_number(r.data, 'USD匯率'), 0), 1) as usd_rate
from public.reports r
join public.profiles p on p.id = r.owner_id;

grant select on public.report_summaries to authenticated;
grant select on public.profiles, public.reports, public.expense_items to authenticated;
grant select on public.countries, public.cities to anon, authenticated;
grant select on public.flight_schedules, public.exchange_rates to authenticated;

-- PostgreSQL grants function execution to PUBLIC by default. Restrict every
-- security-definer mutation to the roles that actually need it.
revoke execute on function public.handle_new_auth_user() from public;
revoke execute on function public.create_report(numeric) from public;
revoke execute on function public.recalculate_report(text) from public;
revoke execute on function public.upsert_expense_item(text,text,integer,jsonb) from public;
revoke execute on function public.delete_expense_item(text,text,integer) from public;
revoke execute on function public.update_report_details(text,text,numeric,date,date,text,text,numeric) from public;
revoke execute on function public.set_report_status(text,text) from public;
revoke execute on function public.delete_report(text) from public;
revoke execute on function public.copy_report(text) from public;
revoke execute on function public.copy_items(text,uuid[]) from public;
revoke execute on function public.sync_report_sequence() from public;
revoke execute on function public.complete_password_reset() from public;
revoke execute on function public.resolve_login(text) from public;

grant execute on function public.create_report(numeric) to authenticated;
grant execute on function public.upsert_expense_item(text,text,integer,jsonb) to authenticated;
grant execute on function public.delete_expense_item(text,text,integer) to authenticated;
grant execute on function public.update_report_details(text,text,numeric,date,date,text,text,numeric) to authenticated;
grant execute on function public.set_report_status(text,text) to authenticated;
grant execute on function public.delete_report(text) to authenticated;
grant execute on function public.copy_report(text) to authenticated;
grant execute on function public.copy_items(text,uuid[]) to authenticated;
grant execute on function public.complete_password_reset() to authenticated;
grant execute on function public.resolve_login(text) to anon, authenticated;
grant execute on function public.recalculate_report(text) to service_role;
grant execute on function public.sync_report_sequence() to service_role;
